# HardcoreBan Configuration

# Ban duration configuration
ban-duration:
  # Time unit: "minutes" or "hours"
  unit: "hours"
  # Amount of time in the specified unit
  amount: 24

# The world that is considered hardcore
# Set to "world" by default
hardcore-world: "world"

# Whether to affect all worlds or just the specified hardcore world
affect-all-worlds: false

# What gamemode to set players to when their ban expires
reset-gamemode: "SURVIVAL"

# Whether to set player to spectator mode on death
# This allows them to see their death location briefly before being kicked
set-spectator-on-death: true

# How long to wait before kicking a player after death (in ticks, 20 ticks = 1 second)
# This only applies if set-spectator-on-death is true
kick-delay-ticks: 60

# How often to check for expired bans (in seconds)
check-interval: 60

# Database configuration
database:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: password

# Logging level
# Available levels: OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL
log-level: "INFO"

# Messages (supports MiniMessage format)
messages:
  death-ban: "<red>You died in hardcore mode! You are banned for {time}."
  kick-message: "<red>You died in hardcore mode! You are banned for {time}."
  join-banned: "<red>You are still banned from hardcore mode for {time}."
  gamemode-reset: "<green>Your hardcore ban has expired. Your gamemode has been set to survival."